# project
title: Xtend
version: 0.6.5
description: Frontend library
homepage: http://getxtend.com/
license: CC Attribution 3.0 Unported
author: Riccardo Caroli <beaver82@gmail.com>
github: "https://github.com/minimit/xtend-library"
download: "https://github.com/minimit/xtend-library/releases"

# settings
host: 127.0.0.1
port: 4000
source: src/docs/
destination: docs/
baseurl:
exclude:
  - "*.psd"
  - "*.less"

# collections
collections:
  docs:
    output: true
    permalink: "/:collection/:path/"
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: sidebar
