name: Release

on:
  push:
    branches:
      - release-0.15
      - release-0.14

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Yarn Install
      run: yarn install --frozen-lockfile
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/git
            @semantic-release/github
            @semantic-release/release-notes-generator
      env:
        GITHUB_TOKEN: ${{ secrets.semantic_release_github_token }}
        NPM_TOKEN: ${{ secrets.semantic_release_npm_token }}
